[package]
name = "crsqlite_example_sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
crsqlite = { workspace = true }
sqlx = { version = "0.8.3", features = ["sqlite"] }
tokio = { version = "1.31", features = ["full"] }
